python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 7
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 8
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 9
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 10
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 11
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 12
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 13
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 14
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 15
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 16
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 17
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 18
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 19
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 20
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 21
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 22
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 23
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 24
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 25
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 26
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 27
python fgfa_rfcn/test2.py --cfg experiments/fgfa_rfcn/cfgs/resnet_v1_101_flownet_jrdb.yaml --ignore_cache --epoc 28
